# Generated by Django 5.1.1 on 2024-10-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="creaated_date",
            new_name="created_date",
        ),
    ]
